---
title: "Plotting modeling results"
output: html_notebook
---
```{r message=FALSE, warning=FALSE}
require(tidyverse)
```

```{r}
# task <- 'estimation'  # or 'face'
task <- 'face'  # or 'face'
output_fn <- paste('outputs/sim-05_task-', task, '_cis.csv', sep='')
imgfn <- paste('img/sim-05_task-', task, sep='')
input_fn <-  paste('outputs/sim-05_task-', task, 
        '_increase_units_increase_voxels_500sim.csv', sep='')
df <- read_csv(input_fn)
df$ratio <- as.factor(df$ratio)
df$b_units <- as.factor(df$b_units)
df <- df %>% group_by(ratio, roi, b_units) %>% select(-X1)
```

# generate bootstrapped values for median and cis
```{r message=FALSE, warning=FALSE, include=FALSE}
# run in batches to reduce memory footprint
if (!file.exists(output_fn)) {
  batches <- 5
  nbs <- 1000
  nbs_batch <- nbs / batches
  set.seed(154254)
  df_bs <- list()
  for (batch in 1:batches) {
    df_batch <- df %>% do(rs=modelr::bootstrap(., nbs_batch)) %>%
      group_by(ratio, roi, b_units) %>%
      unnest() %>%
      group_by(ratio, roi, b_units, .id) %>%
      do(as.data.frame(.$strap)) %>%
      summarise(value=median(value))
    df_batch$.id <- as.numeric(df_batch$.id) + nbs_batch * (batch - 1)
    df_bs <- rbind(df_bs, df_batch)
  }
  
  # compute cis
  ci <- 95
  l_ci <- (100 - ci)/200
  h_ci <- 1 - l_ci
  cis <-
  df_bs %>%
    ungroup() %>%
    group_by(ratio, roi, b_units) %>%
    summarise(lo=quantile(value, l_ci),
              hi=quantile(value, h_ci))
  
  df_t0 <-
    df %>%
    group_by(ratio, roi, b_units) %>%
    summarise(value=median(value))
  
  df_t0 <-
  df_t0 %>%
    merge(cis)
  
  df_t0$roi <- factor(df_t0$roi, levels=c('IOG', 'pFus', 'mFus'))
  write_csv(df_t0, output_fn)
} else {
  df_t0 <- read_csv(output_fn)  
}
```

```{r}
theme_Publication <- function(base_size=12) {
      library(ggthemes)
      (theme_foundation(base_size=base_size)
       + theme(plot.title = element_text(face = "bold",
                                         size = rel(1.2), hjust = 0.5),
               text = element_text(),
               panel.background = element_rect(colour = NA),
               plot.background = element_rect(colour = NA),
               panel.border = element_rect(colour = NA),
               axis.title = element_text(size = rel(1)),
               axis.title.y = element_text(angle=90,vjust =2),
               axis.title.x = element_text(vjust = -0.2),
               axis.text = element_text(), 
               axis.line = element_line(colour="black"),
               axis.ticks = element_line(),
               panel.grid.major = element_blank(), #element_line(colour="#f0f0f0"),
               panel.grid.minor = element_blank(),
               legend.key = element_rect(colour = NA),
               legend.position = "bottom",
               legend.direction = "horizontal",
               #legend.key.size= unit(0.2, "cm"),
               legend.spacing = unit(0, "cm"),
               legend.title = element_text(),
               plot.margin = unit(c(10,5,5,5),"mm"),
               strip.background = element_rect(colour="#f0f0f0",fill="#f0f0f0"),
               strip.text = element_text(face="bold"),
               strip.text.y = element_text(angle = 0)
          ))
      
}

```

```{r fig.height=3.2, fig.width=4}
for (bu in 1:5) {
  if (bu == 1) {
    title <- "unit responsive to b"
  } else {
    title <- "units responsive to b"
  }
  
  df_t0 %>%
    filter(b_units == bu) %>%
    ggplot(aes(ratio, value, ymin=lo, ymax=hi, color=roi, group=roi)) +
    geom_linerange(show.legend=F) +
    geom_line(show.legend=F) +
    geom_point(size=1.5) +
    labs(x="Ratio of units selective to identity a",
         y="Simulated PSE variance",
         color="") +
    ggtitle(paste(bu, title)) +
    theme_Publication() +
    theme(legend.direction='vertical',
          legend.position=c(0.8, 0.8),
          plot.title=element_text(size=12, face='bold')) +
    scale_color_brewer(palette='Set1')
    # coord_cartesian(ylim=y_lims) 
  
  img <- paste(imgfn, '_data_', bu, 'units.png', sep='')
  ggsave(img, dpi=300, height=3.2, width=4)
}
```
